#!/bin/sh
MPATH=`dirname $0`
FOLDER=`echo $1 | sed -e 's/\.apk//g'`
$MPATH/osx/apktool d -f $1
mkdir $FOLDER/src
mv $FOLDER/smali $FOLDER/.smali
$MPATH/dex2jar-2.0/d2j-dex2jar.sh -f -o ${FOLDER}/${FOLDER}_dex2jar.jar $1
echo "Converting .class files to java..."
java -jar $MPATH/jd-cli/jd-core-java-1.2.jar ${FOLDER}/${FOLDER}_dex2jar.jar $FOLDER/src
rm -rf ${FOLDER}_dex2jar.jar
python $MPATH/rreassoc.py ${FOLDER}
